spring.application.name=digital-lucky-draw

#   server config
########################################################################################################################
server.port=8889
logging.file.path=logs/
logging.file.name=./logs/application.logs
server.servlet.context-path=/digital-lucky-draw

#   Database
########################################################################################################################
#UAT
spring.datasource.url=jdbc:oracle:thin:@10.201.214.25:1521/mytel
spring.datasource.username=DAILY_QUEST
spring.datasource.password=DAILY_QUEST
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.jpa.hibernate.ddl-auto=update
#none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
logging.level.org.hibernate.SQL=info
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=info

# Application Login Credentials
app.username=${APP_USERNAME:digital-lucky-draw786}
app.password=${APP_PASSWORD:0l%u#Q|jIP9>SHia}

# Redirect URL after login
app.redirect.url=${APP_REDIRECT_URL:http://localhost:8889}